project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ho Chin Wei"
  favicon: "assets/favicon.webp"
  site-url: "https://hochinwei.com"
  

  page-footer:
    left: "&copy; Copyright 2025, Ho Chin Wei"
    right: "This page is built with [Quarto](https://quarto.org/) in {{< fa brands r-project >}}."

  navbar:
    pinned: true
    logo: "assets/favicon.webp"
    right:

      - text: "About"
        icon: person-raised-hand
        href: about.qmd
        
      - text: "Blog"
        icon: substack
        href: blog.qmd
      
      - text: "Projects"
        icon: tools
        href: projects/index.qmd
        
      - text: "CV"
        icon: file-earmark-richtext
        href: CV.qmd
        
      - text: "Contact"
        icon: person-lines-fill
        href: contact.qmd
            
format:
  html:
    theme: 
      - united
      - styles.scss
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    # code highlight style
    highlight-style: arrow
    icon: fontawesome

extensions:
  - quarto-ext/fontawesome
