project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ho Chin Wei"

  page-footer:
    left: "&copy; Copyright 2025, Ho Chin Wei"
    right: "This page is built with [Quarto](https://quarto.org/)."

  navbar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    right:

      - text: "About me"
        href: about.qmd
        
      - text: "Blog"
        href: blog.qmd
      
      - text: "Projects"
        href: projects/index.qmd

      - text: "Talks"
        href: talks/index.qmd
        
      - text: "Contact"
        href: contact.qmd
            
      - text: "CV"
        href: CV.qmd

format:
  html:
    theme: metro
    css: styles.css
    toc: true
    icon: fontawesome

extensions:
  - quarto-ext/fontawesome
