project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ho Chin Wei"
  favicon: "assets/favicon.png"
  site-url: "https://hochinwei.com"
  

  page-footer:
    left: "&copy; Copyright 2025, Ho Chin Wei"
    right: "This page is built with [Quarto](https://quarto.org/) in {{< fa brands r-project >}}."

  navbar:
    pinned: true
    logo: "assets/favicon.webp"
    right:

      - text: "About me"
        href: about.qmd
        
      - text: "Blog"
        href: blog.qmd
      
      - text: "Projects"
        href: projects/index.qmd
        
      - text: "CV"
        href: CV.qmd
        
      - text: "Contact"
        href: contact.qmd
            
format:
  html:
    theme: 
      - united
      - styles.scss
    toc: true
    icon: fontawesome

extensions:
  - quarto-ext/fontawesome
