name: Daily Telegram Bot Check

on:
  schedule:
    # Every day at 02:00 UTC (adjust if you want a different time)
    - cron: '0 2 * * *'
  workflow_dispatch:    # allows manual trigger

jobs:
  run_bot:
    # 1) Run on the latest Ubuntu runner
    runs-on: ubuntu-latest

    # 2) IMPORTANT: tell Actions to cd into the LinkedIn_games folder
    defaults:
      run:
        working-directory: PersonalWebsite/projects/LinkedIn_games

    steps:
      # 3) Checkout the entire repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 4) Setup R (using r-lib setup)
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      # 5) Install required R packages
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('telegram.bot','openxlsx'), repos='https://cloud.r-project.org')"

      # 6) Run the bot script (which is now in the “LinkedIn_games” subfolder)
      - name: Run telegram_bot.R
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          Rscript datacollect.R
